version: '3.1'

services:
  pg:
    image: postgres
    restart: always
    ports:
      - ${PGPORT}:5432
    env_file: .env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
